spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/yguasu_db
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: INFO
    bo.gob.yguasu: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
