spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/yguasu_db}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

jwt:
  secret: ${JWT_SECRET}

logging:
  level:
    root: WARN
    bo.gob.yguasu: INFO
    org.springframework.web: WARN
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
